### ISSUE TITLE
Segfaults when Bluetooth indicator isn't installed

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-sharing#16]
This plug segfaults when opening if Settings schema 'org.pantheon.desktop.wingpanel.indicators.bluetooth' is not installed, but it doesn't provide or depend on it.

**Comment by torikulhabib** [comment]
fix with this.
pull request soon.
https://github.com/elementary/wingpanel-indicator-bluetooth/issues/124

![Screen record from 2020-08-17 18 21 50](https://user-images.githubusercontent.com/26135527/90392674-88634480-e0b9-11ea-8458-3c2c91dcea5f.gif)

**Comment by danirabbit** [comment]
These days we do runtime depend on the bluetooth indicator https://github.com/elementary/switchboard-plug-sharing/blob/deb-packaging/debian/control
