### ISSUE TITLE
Mention DLNA somewhere

### ISSUE THREAD

**Issue by codygarver** [elementary/switchboard-plug-sharing#26]
We know things are getting shared but we don't know how. TVs mention DLNA support so users need some hint that this does that.

**Comment by danrabbit** [comment]
Yeah that would probably be more useful than the current description text

**Comment by tjchester** [comment]
What about this for new copy (existing copy is highlighted beneath):

"While enabled, files from the selected media libraries are shared to compatible DLNA-enabled devices on your local network such as certain TVs and game consoles."
> "While enabled, the following media libraries are shared to compatible devices in your network."

"While disabled, the selected media libraries are unshared, and files will not be streamed from your computer to other DLNA-enabled devices on your local network."
>"While disabled, the selected media libraries are unshared, and it won't stream files from your computer to other devices."

**Comment by jorgemanzo** [comment]
I've applied tjchester's suggestion on how to word DLNA here: b8d62295e8c798041e5f4d7a807eb013b9ab650d

If its worthy of a pull request I would love to make it one! (This would be my second PR into an open source project so any feedback would be appreciated!)

**Comment by jorgemanzo** [comment]
I've applied tjchester's suggested changes to the enabled/disabled description on my fork here: b8d62295e8c798041e5f4d7a807eb013b9ab650d

If its worthy of a pull request I would love to make one! This would be my second contribution to an open source project!
