### ISSUE TITLE
sharing is always switched off after system restart

### ISSUE THREAD

**Issue by ghabit** [elementary/switchboard-plug-sharing#45]
sharing is always switched off after system restart

**Comment by BAProductions** [comment]
> sharing is always switched off after system restart
> 
> Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/86819622-sharing-is-always-switched-off-after-system-restart?utm_campaign=plugin&utm_content=tracker%2F59965616&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F59965616&utm_medium=issues&utm_source=github).

Ditto

**Comment by ryonakano** [comment]
Hmm, it seems like the autostart file `~/.config/autostart/rygel.desktop` disappears once if we reboot.

**Comment by ryonakano** [comment]
> Hmm, it seems like the autostart file `~/.config/autostart/rygel.desktop` disappears once if we reboot.

Apparently GSD does that, not sure though:

https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/blob/master/plugins/sharing/gsd-sharing-manager.c#L882-905
