### ISSUE TITLE
Build failure with 2.1.4 on Arch Linux

### ISSUE THREAD

**Issue by alucryd** [elementary/switchboard-plug-sharing#47]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Release 2.1.4 fails to build on Arch Linux.

### Logs
https://buildbot.alucryd.xyz/#/builders/25/builds/1/steps/7/logs/stdio

## Platform Information
- OS: Arch Linux
- vala: 0.48.2
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by tintou** [comment]
You seem to build against 2.1.3 which doesn't include the fix

**Comment by alucryd** [comment]
Right, revision hash wasn't updated on my end, thanks!
