### ISSUE TITLE
Make hostname editable

### ISSUE THREAD

**Issue by vjr** [elementary/switchboard-plug-sharing#53]
Related to the discussion in https://github.com/elementary/installer/issues/383 this is a wishlist to make the hostname field configurable, similar to what is available in other OSes like Fedora for example.

Changing the hostname via terminal may be error prone for novice users since apparently you have to edit both `/etc/hostname` and `/etc/hosts` correctly to avoid failure to sudo.

**Comment by ryonakano** [comment]
@danirabbit Do we really want to add this feature in Sharing plug, not in System plug?

The reasons I'm wondering this are:

- Sharing plug does not have any codes related to hostname, but System plug already has some codes to get hostname in `src/Views/HardwareView.vala`. I suppose just adding setting functionally to System plug would be easier for us to implement.
    - Also it would be easier for users to notice that new feature because most users would already know System plug shows hostname since earlier elementary OS versions.
- I don't think setting/getting hostname belongs to any existing pages (neither Media Library or Bluetooth) so I created a dedicated pane for it in my test branch (`ryonakano/add_device_name_page`), which causes the pane looks a little poor:

![screenshot](https://github.com/elementary/switchboard-plug-sharing/assets/26003928/5584a30a-f79f-428b-aae3-820d4e21914b)

I'm not familiar with design things and previous decisions so I'd like to get opinions from you.

**Comment by danirabbit** [comment]
@ryonakano yeah I agree this is probably better done in the system plug. It would be a more natural location for it and we can always link there from here and the Bluetooth plug

**Comment by danirabbit** [comment]
Closing as a duplicate of https://github.com/elementary/switchboard-plug-about/issues/248
