### ISSUE TITLE
 I made some change to switchboard-plugin-sharing but even after I build my changes still do t show up how can I get my change to show up??

### ISSUE THREAD

**Issue by BAProductions** [elementary/switchboard-plug-sharing#59]
### What Happened?

I made some change to switchboard-plugin-sharing but even after I build my changes still do t show up how can I get my change to show up??

### Steps to Reproduce

I made some change to switchboard-plugin-sharing but even after I build my changes still do t show up how can I get my change to show up??

### Expected Behavior

I made some change to switchboard-plugin-sharing but even after I build my changes still do t show up how can I get my change to show up??

### OS Version

6.x (Odin)

### Software Version

Compiled from git

### Log Output

```shell
NA
```

### Hardware Info

LInux VM/ i510500, 16GB of RAM, 1TB M.2 NVME gen3 SSD, no GPU just iGPU,

**Comment by lenemter** [comment]
Are you sure you are installing the plug using `sudo ninja install` after building?

**Comment by BAProductions** [comment]
> using

Yes

**Comment by lenemter** [comment]
Can you post build and install output from terminal here please?

**Comment by BAProductions** [comment]
> Can you post build and install output from terminal here please?

Sure Hold one

**Comment by BAProductions** [comment]
> Can you post build and install output from terminal here please?

Here my repos & my log

https://github.com/MC-OS/switchboard-plug-sharing

[build.log](https://github.com/elementary/switchboard-plug-sharing/files/10546653/build.log)

**Comment by lenemter** [comment]
I guess the problem is that you are executing `meson build` and not `meson build --prefix=/usr` which is a big problem. And please don't execute every command in build instructions with sudo, it can lead to some problems too

**Comment by BAProductions** [comment]
> meson build --prefix=/usr

Bingo please mark as close
